project_id = "kobsfphgfvyjozjwkuhp"

[functions.extract-document]
verify_jwt = false

[functions.verify-carbon]
verify_jwt = false

[functions.calculate-monetization]
verify_jwt = false

[functions.intelligence-chat]
verify_jwt = false
